title: METRICS-E3
description: Explanation and elaboration with examples for METRICS
theme: just-the-docs
logo: "/assets/images/logo.png"

#url: https://just-the-docs.github.io

#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
